### ISSUE TITLE
Full guides on Classic release?

### ISSUE THREAD

**Issue by ujellyx** [max-ri/Guidelime#1]
How confident are you that you can complete the addon or at least the first like 1-40 levels on Classic release?
This looks really promising.

Maybe you can integrate the guides from VanillaGuide?

**Comment by andreas-bylund** [comment]
This addon enables you to make your own guides for classic. So if you have any guide you would like to import, you can do it by yourself. Just follow the [wiki](https://github.com/max-ri/Guidelime/wiki/WriteAGuide)

**Comment by max-ri** [comment]
I am very much confident that there will be a full guide at launch or at least very shortly after for alliance. For Horde i am not so sure yet but there definitely also will be a guide.
I am trying to include any guide that the respective author has given me the permission to use. I am afraid the guide you mentioned does not fall under this category.
But as andreas-bylund wrote, you can very much take any guide you find and put it into the addon yourself.
