### ISSUE TITLE
Addon crashing on load

### ISSUE THREAD

**Issue by daniandr** [max-ri/Guidelime#102]
Hello,

After completing a step the addon crashed and it now crashes everytime i reload UI or relog with the following error

> Date: 2019-08-31 18:20:07
> ID: 1
> Error occured in: Global
> Count: 1
> Message: ..\AddOns\Guidelime\Guidelime.lua line 333:
>    attempt to index field 'lastStep' (a nil value)
> Debug:
>    [C]: ?
>    Guidelime\Guidelime.lua:333: loadCurrentGuide()
>    Guidelime\Guidelime.lua:234: loadData()
>    Guidelime\Guidelime_Events.lua:12: ?()
>    Guidelime\Guidelime_Events.lua:6:
>       Guidelime\Guidelime_Events.lua:5
> Locals:
> 
> AddOns:
>   Swatter, v8.2.6377 (SwimmingSeadragon)
>   AtlasLootClassic, vv1.1.7-beta1
>   Auctionator, v8.1.0
>   BeanCounter, v8.2.6381 (SwimmingSeadragon)
>   DBMCore, v1.13.3
>   DBMDefaultSkin, v
>   DBMStatusBarTimers, v
>   Details, v
>   DetailsTinyThreat, v
>   Guidelime, v1.010
>   GuidelimeJudgementAlliance160, v0.1337 beta
>   Prat30, v3.2.30
>   Prat30Libraries, v
>   Questie, v4.0.12 BETA
>   SlideBar, v8.2.6375 (SwimmingSeadragon)
>   Stubby, v8.2.6376 (SwimmingSeadragon)
>   TradeSkillMaster, vv4.8.2
>   TradeSkillMasterAppHelper, vv4.0.3
>   WeakAuras, v2.14.6
>   BlizRuntimeLib_enUS v1.13.2.11302 <none>
>   (ck=245)
> 
> 

This is in WoW Classic

**Comment by m33ts4k0z** [comment]
Same error here

**Comment by max-ri** [comment]
ty for reporting
