### ISSUE TITLE
Github Guides

### ISSUE THREAD

**Issue by MaxoCream** [max-ri/Guidelime#105]
I've had a pleasure using this add-on and this has been very helpful to my classic experience. I have found the guides provided to be very helpful but occasionally vague or sometimes completely outdated. This brings to my a thought I had. I was curious about working on an open sourced guide, much like Guidelime on GitHub. If this is something that is already happening, great and can you please link me? But if not, I can only imagine the potential size and detail having an open sourced guide could offer. If someone felt like making an unique mount guide that could be added in, profession guides, etc. I'm getting ahead of myself.

I guess I want to know if this is something that anyone sees as actual value, surely the devs have considered something of this nature. Because I would happily start on a little something to get the ball rolling and work from that point.

**Comment by max-ri** [comment]
Several of the guides are already maintained on github. But they all are credited to one author. There is not an open source guide where anyone can contribute freely yet. On the other hand, all of the authors would surely be happy to get feedback on how to improve their guides. Feel free to send them your comments.
Check out the wiki of this project. You will find links to all the guides and instructions on how to create an open source guide repository on your own if you would like to do that.
