### ISSUE TITLE
Bustea's 21-31 - Quest Number 12,13,14

### ISSUE THREAD

**Issue by aldaw** [max-ri/Guidelime#106]
Right now it is:
12 - Hearth to Orgrimmar
13 - Look for Senani Thunderheart and accept The Ashevale Hunf
14 - Fly to Splintertree Post

13 and 14 must be swaped.

And when you are in Orgrimmar he guide you wrongly to "The Valley of Spirits".

Thanks for all the efforts and time! :)

**Comment by aldaw** [comment]
i caint solve also 16 oO - Talk to her again, accept The Ahshenvale Hunt and turn it back in

**Comment by max-ri** [comment]
fixed by bustea
