### ISSUE TITLE
Skipping an optional breadcrumb skips the entire quest chain.

### ISSUE THREAD

**Issue by edkimmel** [max-ri/Guidelime#107]
Q 473 Report to Captain Stoutfist is listed as a Prereq for Q 464 War Banners.  Report to Captain Stoutfist is an optional breadcrumb quest. Skipping this breadcrumb should not mark the rest of the chain as skipped, as I can still pick up War Banners and continue as normal.

**Comment by max-ri** [comment]
just confirmed myself 464 can be accepted without having done 473
also i cannot accept 473. classicdb comment suggests it has 455 as prequest
confirmed: 473 can be accepted after completing 455

**Comment by max-ri** [comment]
fixed
