### ISSUE TITLE
Question: Can I hop into a guide half way through?

### ISSUE THREAD

**Issue by ryanmortier** [max-ri/Guidelime#110]
I've manually been following the Alliance Judgement guide from the Google docs and I'm currently level 32. Can I install Guidelime + the Judgement guide and it will automatically pick up my progress or how does that work?

**Comment by JanRK** [comment]
Guidelime will automatically complete steps for quests you've already done. So shouldn't be a big problem to start even if you're 32. Most guides are split up into sections. From 10-20, 20-30, 1-6 etc, making it easier for you.

**Comment by max-ri** [comment]
Yeah and if you continue with Judgements guide you will have no problem at all since you will already have done all the correct quests.
