### ISSUE TITLE
Request: Allow auto turnin for quests outside of the current step of the guide.

### ISSUE THREAD

**Issue by wejrox** [max-ri/Guidelime#114]
**What?**
I've been following a guide but quests only seem to be auto turned in when I'm on the step that links/mentions handing them in. 
It would be useful to have an option to auto turn in any quests that are contained within the current guide, *whether or not* I'm on the step that explicitly links/mentions it. 

**Why?**
This would be a convenient QoL change because sometimes I'm in an area (for other reasons) which contains a complete quest that is mentioned later on in the guide and would like it to auto turn-in to save time.

**Comment by Zarant** [comment]
If you ever entertain the idea of implementing this feature please make sure that it isn't active by default.
There are few cases where the order in which you turn in quests is very important, since some quests can start a long ass RP sequence once you turn it in.

**Comment by max-ri** [comment]
idea: 
adding the following new options
`automatically accept (X) quests referenced in the current steps ( ) quests referenced in the current guide ( ) all quests`
`automatically turn-in (X) quests referenced in the current steps ( ) quests referenced in the current guide ( ) all quests`
