### ISSUE TITLE
Latest commit not working

### ISSUE THREAD

**Issue by nymann** [max-ri/Guidelime#115]
Commit that I have tried: #26aa177578b907e0c395b5e72badf4c251dad0d7

Getting many Lua errors:
```
Message: Interface\AddOns\Guidelime\Guidelime.lua:1492: '<eof>' expected near 'end'
Time: Sun Sep 29 09:23:19 2019
Count: 1
Stack: Interface\AddOns\Guidelime\Guidelime.lua:1492: '<eof>' expected near 'end'

Locals:
```

The rest of the 60 lua errors is due to trying to access nil values due to the first error.

Previous version (I don't know which one it was, worked fine)

OS: Arch Linux
Playing wow through Lutris.

Symlinked Guidelime/Guidelime to addons folder.

**Comment by nymann** [comment]
Version 1.032 from Curseforge is working as intended.

**Comment by nymann** [comment]
Just to ensure it's not on my end, I also tried to simply follow the suggested install method (downloading Guidelime-master.zip) and putting the Guidelime-master/Guidelime folder into my addOns folder directly without symlinking. Same result as my first post.

**Comment by max-ri** [comment]
yeah my bad! just fixed it. :)
