### ISSUE TITLE
Poor Indicator Placement - Step 85 of Bustea Horde 36-41

### ISSUE THREAD

**Issue by Kechlion** [max-ri/Guidelime#121]
Not a huge deal, but the indicator for step 85 of the Horde side guide for 36-41 states 

"Grind your way ontop of the Oil Rig and kill Foreman Cozzle, loot his key and then open the chest at [guide arrow] for [37] Goblin Sponsorship"

The guide arrow is pointing to 41.9, 20.2 which is in the middle of the lake. The actual chest location is around 43.3, 20.3.

![image](https://user-images.githubusercontent.com/60458868/81172535-0b75ea00-8f64-11ea-8de4-5480dd16dace.png)

**Comment by max-ri** [comment]
this would be an error in busteas guide then and not in guidelime.
thanks for reporting and sorry for you having to wait for so long.
forwarded to bustea.
