### ISSUE TITLE
Disabling Demo guides prevents full versions of those guides from appearing

### ISSUE THREAD

**Issue by fusionpit** [max-ri/Guidelime#122]
I had guidelime 1.040 and https://www.curseforge.com/wow/addons/guidelime_tugs installed at the same time.  Unchecking "Display Demo Guides" in the options will make the "Available Guides" list empty.  Checking it will show both the demo and full version of TUG's guide.

**Comment by max-ri** [comment]
Fixed.
Thanks for reporting.
Sorry for having to wait for so long. ;)
