### ISSUE TITLE
Feature Request: Support For Vanilla WoW (1.12) for Private Servers

### ISSUE THREAD

**Issue by jsleep** [max-ri/Guidelime#128]
Hey I really like playing on a specific private server. What changes would be necessary to support both? I work as a programmer and want to learn how to port the addon for 1.12 but know next to nothing when it comes WoW addons.

**Comment by Zarant** [comment]
I've looked into it myself, it's A LOT of work, the 1.12 API is missing a LOT of stuff, things like step auto completion, and waypoint management are very hard to do with the old API.
I started making a modified version of [VanillaGuide](https://github.com/Zarant/VanillaGuide) to accomplish that, but honestly I don't have the time required to finish this project.
I think your best bet is using that as a starting point and then coming up with a way to parse Guidelime guides into that framework
