### ISSUE TITLE
TBC Beta - accessing options produces errors

### ISSUE THREAD

**Issue by shawn571** [max-ri/Guidelime#134]
These errors appear when right-clicking the Guidelime window to select a guide, or access it from Interface menu:

Message: Interface\FrameXML\InterfaceOptionsFrame.lua:423: attempt to index global 'InterfaceOptionsFrameTab1TabSpacer' (a nil value)
Time: Thu Apr  1 07:37:55 2021
Count: 1
Stack: Interface\FrameXML\InterfaceOptionsFrame.lua:423: attempt to index global 'InterfaceOptionsFrameTab1TabSpacer' (a nil value)
[string "@Interface\FrameXML\InterfaceOptionsFrame.lua"]:423: in function InterfaceOptionsFrame_TabOnClick'
[string "*:OnClick"]:3: in function <[string "*:OnClick"]:1>
[string "=[C]"]: in function Click'
[string "@Interface\FrameXML\InterfaceOptionsFrame.lua"]:476: in function InterfaceOptionsFrame_OpenToCategory'
[string "@Interface\AddOns\Guidelime\Guidelime_Guides.lua"]:275: in function func'
[string "@Interface\FrameXML\UIDropDownMenu.lua"]:960: in function `UIDropDownMenuButton_OnClick'
[string ":OnClick"]:1: in function <[string ":OnClick"]:1>

Message: Interface\FrameXML\InterfaceOptionsFrame.lua:158: attempt to index global 'InterfaceOptionsFrameCategoriesTop' (a nil value)
Time: Thu Apr  1 07:37:55 2021
Count: 1
Stack: Interface\FrameXML\InterfaceOptionsFrame.lua:158: attempt to index global 'InterfaceOptionsFrameCategoriesTop' (a nil value)
[string "@Interface\FrameXML\InterfaceOptionsFrame.lua"]:158: in function InterfaceAddOnsList_Update'
[string "@Interface\FrameXML\InterfaceOptionsFrame.lua"]:393: in function <Interface\FrameXML\InterfaceOptionsFrame.lua:389>
[string "=[C]"]: in function Show'
[string "@Interface\FrameXML\InterfaceOptionsFrame.lua"]:204: in function InterfaceOptionsFrame_Show'
[string "@Interface\FrameXML\InterfaceOptionsFrame.lua"]:487: in function InterfaceOptionsFrame_OpenToCategory'
[string "@Interface\AddOns\Guidelime\Guidelime_Guides.lua"]:275: in function func'
[string "@Interface\FrameXML\UIDropDownMenu.lua"]:960: in function UIDropDownMenuButton_OnClick'
[string ":OnClick"]:1: in function <[string ":OnClick"]:1>

See https://github.com/Stanzilla/WoWUIBugs/issues/77 for possible fix ideas

**Comment by max-ri** [comment]
Was a Blizzard issue. Has been fixed.
