### ISSUE TITLE
TBC Beta - Newly copied character produces errors

### ISSUE THREAD

**Issue by shawn571** [max-ri/Guidelime#135]
This only happens when copying a character from Classic to TBC Beta and logging on the first time. This does not happen after a logout/logon or when creating a new character on TBC Beta. Might be a TBC Beta only issue that won't be present when it's live but will report here.

Message: Interface\AddOns\Guidelime\Guidelime_Events.lua:446: attempt to index global 'GuidelimeDataChar' (a nil value)
Time: Tue Apr  6 09:17:37 2021
Count: 8
Stack: Interface\AddOns\Guidelime\Guidelime_Events.lua:446: attempt to index global 'GuidelimeDataChar' (a nil value)
[string "@Interface\AddOns\Guidelime\Guidelime_Events.lua"]:446: in function `?'
[string "@Interface\AddOns\Guidelime\Guidelime_Events.lua"]:6: in function <Interface\AddOns\Guidelime\Guidelime_Events.lua:5>

**Comment by max-ri** [comment]
This might or might not have anything do with TBC Beta at all. Might just be a sporadic timing issue with the bag update event.
Fixed easily anyway.
