### ISSUE TITLE
Issue with Gnomeregan cloth quests

### ISSUE THREAD

**Issue by Dessyreqt** [max-ri/Guidelime#136]
![image](https://user-images.githubusercontent.com/12574786/116277677-54154d00-a74b-11eb-9be0-aa3ae8ab595e.png)

In the above image you can see the the Gnomeregan Mageweave quest is marked as "skipped" where the Ironforge quest is not. This happened automatically while playing through the Guidelime_Zarant guide. 

Here is what is in the guide for these steps:

```
[G43.22,31.57Ironforge]Do the Gnomeregan cloth turn ins:\\[QA7807-][O][QT7807-][O]Wool \\[QA7808-][O][QT7808-][O]Silk \\[QA7809-][O][QT7809-][O]Mageweave
[G43.22,31.57Ironforge]Do the Ironforge cloth turn ins:\\[QA7802-][O][QT7802-][O]Wool \\[QA7803-][O][QT7803-][O]Silk \\[QA7804-][O][QT7804-][O]Mageweave
```

The intention is to turn in Wool, Silk, then Mageweave in one go for both Gnomeregan and Ironforge. If I hadn't been paying attention to the skipped quests I wouldn't have noticed this as I normally play without skipped steps enabled.

**Comment by max-ri** [comment]
Thanks for reporting. There was an issue with the Ironforge donation quests in the database.
Cloth donation quests were all a bit messed up in the database somehow. I hope now they are finally all sorted out.
