### ISSUE TITLE
arrow not shown

### ISSUE THREAD

**Issue by jaydeshow** [max-ri/Guidelime#137]
beta
Interface: 20501

arrowFrame was not shown

![WoWScrnShot_050621_211604](https://user-images.githubusercontent.com/14103376/117335696-011b6280-aece-11eb-9f28-96fa942d113d.jpg)

**Comment by max-ri** [comment]
This is an issue with Zarant's guide not with Guidelime.
Please report this to https://github.com/Zarant/Guidelime_Zarant.
Thank You!
