### ISSUE TITLE
Get the Versions right.

### ISSUE THREAD

**Issue by Arby69** [max-ri/Guidelime#141]
I observe some weeks now, that you use 1.13.6 for classic era and 1.13.7 for BCC version.
That is not correct in my opinion. Classic Era is 1.13.7 now (since the pre patch) and TBC/BCC is actually 2.5.1.

**Comment by max-ri** [comment]
To be honest I have no clue what you are talking about.
Where do you see these versions?
For Classic Era I use Interface number 11307.
For TBC 20501. (Look into Guidelime.toc and you will see it.)
These are the correct numbers as can be found eg on https://wowpedia.fandom.com/wiki/Template:API_LatestInterface.
As soon as these are change I will adjust both versions on Curseforge. (Here on Github the latest version will usually contain the TBC number.)

**Comment by max-ri** [comment]
Also if you look on Curseforge https://www.curseforge.com/wow/addons/guidelime/files you can see all files uploaded there are marked for the correct respective game version. If Curseforge app is showing otherwise, it is a problem of the app.
