### ISSUE TITLE
Gnome Warlock Beginnings quest - lists a pre-req when there isn't one

### ISSUE THREAD

**Issue by Starsoar** [max-ri/Guidelime#143]
When going to accept quest id 1599 at level 4 warlock "Beginning", Guidelime lists a prereq when there is none. 

["sort"] = "Warlock";
	   ["classes"] = {
	      [1] = "Warlock";
	   };
	   ["deliver"] = {
	      [1] = {
	         ["id"] = 460;
	         ["type"] = "npc";
	      };
	   };
	   ["faction"] = "Alliance";
	   ["name"] = "Beginnings";
	   ["level"] = 4;
	   ["source"] = {
	      [1] = {
	         ["id"] = 460;
	         ["type"] = "npc";
	      };
	   };
	   ["req"] = 1;

Located in Guidelime_QuestsDB.lua

**Comment by max-ri** [comment]
There is no pre-req for this quest. ["req"] = 1 means the level required for accepting the quest.
