### ISSUE TITLE
Error 132 ACCESS_VIOLATION

### ISSUE THREAD

**Issue by Esgariot** [max-ri/Guidelime#145]
Hi, I think this add-on causes access_violation error on my TBC Classic WoW instance in Wine, linux.

After filtering down `.toc` it looks like it definitely comes from one of these:

```
Libs\LibStub\LibStub.lua
Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua
Libs\HereBeDragons\HereBeDragons-2.0.lua
Libs\HereBeDragons\HereBeDragons-Pins-2.0.lua

Localization.lua
Data\Guidelime_Data.lua
Guidelime.lua
```
though I don't know which one yet and why. I'll try to post updates.

**Comment by max-ri** [comment]
Please update to current version. Meanwhile I will close this and reopen in case you still get the error. Try to get the exact message (installing BugGrabber+BugSack would help) and post here.
