### ISSUE TITLE
' in quest name stuck entire guide

### ISSUE THREAD

**Issue by Lilianos** [max-ri/Guidelime#148]
Hi,
Steps with questname containing a ' like `[QA12814 You'll Need a Gryphon]` generate errors like:

Stack: Interface\AddOns\Guidelime\Guidelime_QuestLog.lua:51: attempt to index local 'questLogTitle' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\Guidelime\Guidelime_QuestLog.lua"]:51: in function <Interface\AddOns\Guidelime\Guidelime_QuestLog.lua:5>
[string "=[C]"]: ?
This seem's to stuck following steps
Maybe you already know it or there is a solution, sorry
Btw i'm using Guidelime-v2.031(WOTLK) version and playing wotlk beta

**Comment by max-ri** [comment]
Please update to v2.034(WOTLK). This will fix the error you are seeing.
This bug has nothing to do with the ' in the name. Just tested it myself. Should not make a problem.
