### ISSUE TITLE
Integration with Questie problems

### ISSUE THREAD

**Issue by MyTechnoHunter** [max-ri/Guidelime#150]
Questie is refactoring to make things easier/better with WotLK and thus is changing the questieDB end of things..

the following occurs when loading questie version 7.0.2
and guidelime v2.038 (WotLK)

2x Questie\Database\QuestieDB.lua:370: Usage: GetQuestTagInfo(questID)
[string "=[C]"]: in function `GetQuestTagInfo'
[string "@Questie\Database\QuestieDB.lua"]:370: in function `GetQuestTagInfo'
[string "@Questie\Database\QuestieDB.lua"]:333: in function `IsDungeonQuest'
[string "@Guidelime\Data\Guidelime_Questie.lua"]:91: in function <Guidelime\Data\Guidelime_Questie.lua:89>
[string "=(tail call)"]: ?
[string "@Guidelime\Guidelime-2.038.lua"]:640: in function `getQuestText'
[string "@Guidelime\Guidelime_Map.lua"]:129: in function <Guidelime\Guidelime_Map.lua:124>
[string "@Guidelime\Guidelime_Map.lua"]:161: in function `addMapIcon'
[string "@Guidelime\Guidelime-2.038.lua"]:1233: in function `updateStepsMapIcons'
[string "@Guidelime\Guidelime-2.038.lua"]:1314: in function `updateSteps'
[string "@Guidelime\Data\Guidelime_Questie.lua"]:40: in function <Guidelime\Data\Guidelime_Questie.lua:36>

Locals:
(*temporary) = <table> {
 objectCompilerOrder = <table> {
 }
 questDataOverrides = <table> {
 }
 _QueryItemSingle = <function> defined @Questie\Database\compiler.lua:1161
 itemCompilerOrder = <table> {
 }
 questKeys = <table> {
 }
 questFlags = <table> {
 }
 objectDataOverrides = <table> {
 }
 _npcAdapterQueryOrder = <table> {
 }
 NPCPointers = <table> {
 }
 IsActiveEventQuest = <function> defined @Questie\Database\QuestieDB.lua:382
 ObjectPointers = <table> {
 }
 IsComplete = <function> defined @Questie\Database\QuestieDB.lua:602
 factionTemplate = <table> {
 }
 IsParentQuestActive = <function> defined @Questie\Database\QuestieDB.lua:436
 objectKeys = <table> {
 }
 questCompilerTypes = <table> {
 }
 objectKeysReversed = <table> {
 }
 QueryNPC = <function> defined @Questie\Database\QuestieDB.lua:153
 _QueryQuestSingle = <function> defined @Questie\Database\compiler.lua:1161
 QuestPointers = <table> {
 }
 GetQuestsByZoneId = <function> defined @Questie\Database\QuestieDB.lua:995
 itemKeys = <table> {
 }
 GetQuestTagInfo = <function> defined @Questie\Database\QuestieDB.lua:369
 GetNPC = <function> defined @Questie\Database\QuestieDB.lua:944
 _itemAdapterQueryOrder = <table> {
 }
 IsRaidQuest = <function> defined @Questie\Database\QuestieDB.lua:339
 npcDataOverrides = <table> {
 }
 GetQuest = <function> defined @Questie\Database\QuestieDB.lua:642
 questCompilerOrder = <table> {
 }
 npcKeys = <table> {
 }
 itemDataOverrides = <table> {
 }
 raceKeys = <table> {
 }
 questKeysReversed = <table> {
 }
 fakeTbcItemStartId = 40000
 itemCompilerTypes = <table> {
 }
 IsExclusiveQuestInQuestLogOrComplete = <function> defined @Questie\Database\QuestieDB.lua:388
 objectCompilerTypes = <table> {
 }
 sortKeys = <table> {
 }
 QueryItemSingle = <function> defined @Questie\Database\QuestieDB.lua:153
 Initialize = <function> defined @Questie\Database\QuestieDB.lua:168
 QueryObject = <function> defined @Questie\Database\QuestieDB.lua:153
 ItemPointers = <table> {
 }
 QueryObjectSingle = <function> defined @Questie\Database\QuestieDB.lua:153
 _questAdapterQueryOrder = <table> {
 }
 _QueryObjectSingle = <function> defined @Questie\Database\compiler.lua:1161
 QueryQuestSingle = <function> defined @Questie\Database\QuestieDB.lua:153
 _QueryItem = <function> defined @Questie\Database\compiler.lua:1188
 npcCompilerOrder = <table> {
 }
 QueryItem = <function> defined @Questie\Database\QuestieDB.lua:153
 _QueryQuest = <function> defined @Questie\Database\compiler.lua:1188
 _QueryNPC = <function> defined @Questie\Database\compiler.lua:1188
 IsLevelRequirementsFulfilled = <function> defined @Questie\Database\QuestieDB.lua:405
 _QueryNPCSingle = <function> defined @Questie\Database\compiler.lua:1161
 _CreatureLevelCache = <table> {
 }
 GetZoneOrSortForClass = <function> defined @Questie\Database\QuestieDB.lua:361
 IsPreQuestSingleFulfilled = <function> defined @Questie\Database\QuestieDB.lua:477
 private = <table> {
 }
 GetCreatureLevels = <function> defined @Questie\Database\QuestieDB.lua:902
 _QueryObject = <function> defined @Questie\Database\compiler.lua:1188
 IsPreQuestGroupFulfilled = <function> defined @Questie\Database\QuestieDB.lua:448
 IsDoable = <function> defined @Questie\Database\QuestieDB.lua:503
 npcFlags = <table> {
 }
 QueryQuest = <function> defined @Questie\Database\QuestieDB.lua:153
 IsRepeatable = <function> defined @Questie\Database\QuestieDB.lua:317
 classKeys = <table> {
 }
 itemKeysReversed = <table> {
 }
 _objectAdapterQueryOrder = <table> {
 }
 IsDailyQuest = <function> defined @AddO

**Comment by BreakBB** [comment]
Questie Dev here: Easy fix. We refactored parts of the QuestieDB module to improve performance. SImply call `QuestieDB.IsDungeonQuest` instead of `QuestieDB:IsDungeonQuest`. Same goes for a few other QuestieDB functions.

**Comment by max-ri** [comment]
Thank you Björn!
Great support from you guys.

**Comment by BreakBB** [comment]
You are welcome @max-ri We know your addon is quite popular as well, so its good to stick together 😉
