### ISSUE TITLE
performance stuttering / hitching with a specific quest being tracked

### ISSUE THREAD

**Issue by doubledgedboard** [max-ri/Guidelime#152]
related to #123 

I'm tracking https://www.wowhead.com/wotlk/quest=20/blackrock-menace as part of a leveling guide

When this quest specifically is the current active quest, I get regular stuttering/hitching of the game client.

I did testing of disabling all addons and enabling specific ones until identifying this as the source. It does not seem to be affected by interactions with Questie, for example.

As per the image, the quest itself has a large number of targetable NPCs so perhaps this could be related. Until this quest, I haven't noticed a performance issue.

![image](https://user-images.githubusercontent.com/5682150/196514049-8262eb0d-15b9-4ccf-a49a-e19e083194f4.png)

Please let me know if I can help by providing any additional information. Not sure if this is something directly fixable, but hopefully it's at least a data point for your performance optimizations.

**Comment by max-ri** [comment]
Thanks for the detailed report. This helps a lot!
Should be solved with latest release 3.013.
