### ISSUE TITLE
Game freezes every few seconds while step window is open.

### ISSUE THREAD

**Issue by Riddiks** [max-ri/Guidelime#153]
The game starts stuttering while using Guidelime with either Questie or CalssicCodex but only if the Step Window is open. Just having Guidelime and Questie enabled with the window closed lets the game run perfectly fine. but with the window opened , the game keeps on freezing for a second or two. Im using the latest versions of both guidelime and questie on wotlk classic.

**Comment by max-ri** [comment]
Duplicate to #152
Should be solved with latest release 3.013.
Ty for reporting!
