### ISSUE TITLE
hidden scroll bars still clickable

### ISSUE THREAD

**Issue by MyTechnoHunter** [max-ri/Guidelime#155]
Guidelime for WoTLK, latest version
i have the scroll bar s hidden and the target icons on the right hand side instead of the left
using the guide, if i click on the icon in the middle of the thing is doesnt highlight the icon (to click) instead it clicks the guide itself to move it around like if the scroll bar was visible.

verified by movin the mouse lower than a clickable icon (thinking it might be a artifact of the icon somehow) but clicking on nothing but the screen where the scroll bar would be shifts the guide that far..

**Comment by max-ri** [comment]
Thanks for reporting. Will be fixed with the next update!

**Comment by MyTechnoHunter** [comment]
ty kindly!
