### ISSUE TITLE
missing libs in classic version

### ISSUE THREAD

**Issue by MyTechnoHunter** [max-ri/Guidelime#159]
posted in the discord bug channel, putting here for clarity

Guidelime-Classic.toc file is missing the following lines
Libs\LibDataBroker-1.1\LibDataBroker-1.1.lua
Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua

**Comment by max-ri** [comment]
Indeed.
Thanks for pointing out. Will be fixed with the next update.
