### ISSUE TITLE
LUA Error with Guidelime

### ISSUE THREAD

**Issue by Mogorain** [max-ri/Guidelime#166]
The below error appears even when I disable all addons EXCEPT guidelime and TUG's guide.  It's rather inconsistent in when it happens -- which disables the guide window (blank window) -- or remains functional.

Message: Interface_Wrath/FrameXML/TargetFrame.lua:931: attempt to perform arithmetic on local 'raidTargetIconIndex' (a nil value)
Time: Wed Aug 30 22:50:13 2023
Count: 1
Stack: Interface_Wrath/FrameXML/TargetFrame.lua:931: attempt to perform arithmetic on local 'raidTargetIconIndex' (a nil value)
[string "@Interface_Wrath/FrameXML/TargetFrame.lua"]:931: in function `SetRaidTargetIconTexture'
[string "@Interface/AddOns/Guidelime/ActionButtons.lua"]:202: in function `updateTargetButtons'
[string "@Interface/AddOns/Guidelime/CurrentGuide.lua"]:1116: in function `updateSteps'
[string "@Interface/AddOns/Guidelime/MainWindow.lua"]:240: in function `updateMainFrame'
[string "@Interface/AddOns/Guidelime/MainWindow.lua"]:398: in function `showMainFrame'
[string "@Interface/AddOns/Guidelime/Events.lua"]:35: in function <Interface/AddOns/Guidelime/Events.lua:33>

Locals: texture = nil
raidTargetIconIndex = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'raidTargetIconIndex' (a nil value)"

**Comment by max-ri** [comment]
Thank you for reporting this bug.
This will be fixed with the next update.
