### ISSUE TITLE
Guidelime does not appear to be tracking quest loot

### ISSUE THREAD

**Issue by Rorthron** [max-ri/Guidelime#168]
I've noticed that Guidelime is no longer tracking quests properly for me. 

![image](https://github.com/max-ri/Guidelime/assets/44713088/0d73c953-2f46-4f03-a4ef-07d965e208b5)

Here I have done a quest in Borean Tundra and looted the item, but Guidelime still thinks I need to do it. Is this a problem with Guidelime or perhaps the TUG quest?

To resolve I have to reload UI. When I do the addon notices the item in the bag and continues, but this is not really viable and makes the addon unusable at the moment.

**Comment by Rorthron** [comment]
An update. It appears that it resolves itself when I open the quest tracker and open up the quests for the zone I am in. 

![image](https://github.com/max-ri/Guidelime/assets/44713088/5cafb514-6efb-498e-a166-8069fffc82af)

When I open the zone, the addon refreshes and I am up to date again
![image](https://github.com/max-ri/Guidelime/assets/44713088/68056204-5ee6-4794-acc0-cc58c6577523)

Could this be an issue with another addon causing issues? I am using Questie as my source.

**Comment by MyTechnoHunter** [comment]
Are both questie and guidelime up to date?

**Comment by Rorthron** [comment]
Yes

**Comment by max-ri** [comment]
What other addons do you have installed? Does this keep happening with only Guidelime and Questie?
