### ISSUE TITLE
Problem installing addon (Libstub folder)

### ISSUE THREAD

**Issue by Juohmaru94** [max-ri/Guidelime#170]
**Why does this pop up? I am playing on a vanilla private server 1.12.1 if that helps.**
**Also in the character screen it says that the addon is out of date, while I have downloaded the most recent version**

![problem](https://github.com/max-ri/Guidelime/assets/101858127/886d339a-4609-4233-8686-50133a533fc9)

**Comment by MyTechnoHunter** [comment]
Interface version number triggers out of date if smaller _OR_ larger than game version
