### ISSUE TITLE
Check class/race restrictions of quests (in particular #6387 Honor Students)

### ISSUE THREAD

**Issue by Truth-** [max-ri/Guidelime#47]
While leveling on the Stresstest a guide i was following wanted me to pick up and complete https://classic.wowhead.com/quest=6387/honor-students this quest wasn't race locked on private servers but seems to be on real Classic.

Now i noticed that questie had filtered this quest correctly and didn't show it to be available. A validation when loading/import/create a guide that would check for quests that lack the correct race + class restrictions would be cool.

``
['requiredRaces'] = 6, -- bitmask
['requiredClasses']` = 7, -- bitmask
``

**Comment by max-ri** [comment]
Changed issue title. What you suggested is already implemented. Whenever a guide uses a restricted quest, restrictions are applied automatically. The [A] tag in this case is optional and can additionally be used for better readability.
In this case the problem is rather the restriction on the specific quest not being present in the quest database.

**Comment by Truth-** [comment]
I know that the [A] tag exist. My proposition was to add sanity/validation checks to poorly written that forgot or didn't use the [A] tag. This could be done by using the Questie's DB etc.

**Comment by max-ri** [comment]
There is a validation already when [A] is missing: the missing [A] is simply added in appropriately. Thats was i meant with restrictions are applied automatically. Only instead of Questie the internal database is used.
It would make sense though to also use Questie instead of the internal database when checking for quest restrictions when the option "Use Questie as data source" is selected. This is currently not the case.

**Comment by max-ri** [comment]
https://classicdb.ch/?quest=6181; first comment suggests 6181,6387,6344,9603 all are race specific.
![grafik](https://user-images.githubusercontent.com/51713394/64920393-8ad96200-d7b7-11e9-904d-0d45bc538926.png)

**Comment by max-ri** [comment]
confirmed: cant accept a swift message as gnome

**Comment by max-ri** [comment]
added these corrections:

-- race restrictions on quest chains introducing flight paths
addon.questsDB[6181].race = {"Human"}            -- A Swift Message
addon.questsDB[6281].race = {"Human"}            -- Continue to Stormwind
addon.questsDB[6261].race = {"Human"}            -- Dungar Longdrink
addon.questsDB[6285].race = {"Human"}            -- Return to Lewis
addon.questsDB[6387].race = {"Dwarf", "Gnome"}   -- Honor Students
addon.questsDB[6391].race = {"Dwarf", "Gnome"}   -- Ride to Ironforge
addon.questsDB[6388].race = {"Dwarf", "Gnome"}   -- Gryth Thurden
addon.questsDB[6392].race = {"Dwarf", "Gnome"}   -- Return to Brock
addon.questsDB[6344].race = {"NightElf"}         -- Nessa Shadowsong
addon.questsDB[6341].race = {"NightElf"}         -- The Bounty of Teldrassil
addon.questsDB[6342].race = {"NightElf"}         -- Flight to Auberdine
addon.questsDB[6343].race = {"NightElf"}         -- Return to Nessa
addon.questsDB[6365].race = {"Orc", "Troll"}     -- Meats to Orgrimmar
addon.questsDB[6384].race = {"Orc", "Troll"}     -- Ride to Orgrimmar
addon.questsDB[6385].race = {"Orc", "Troll"}     -- Doras the Wind Rider Master
addon.questsDB[6386].race = {"Orc", "Troll"}     --	Return to the Crossroads
addon.questsDB[6361].race = {"Tauren"}           -- A Bundle of Hides
addon.questsDB[6362].race = {"Tauren"}           -- Ride to Thunder Bluff
addon.questsDB[6363].race = {"Tauren"}           -- Tal the Wind Rider Master
addon.questsDB[6364].race = {"Tauren"}           -- Return to Jahan
addon.questsDB[6321].race = {"Undead"}           -- Supplying the Sepulcher
addon.questsDB[6323].race = {"Undead"}           -- Ride to the Undercity
addon.questsDB[6322].race = {"Undead"}           -- Michael Garrett
addon.questsDB[6324].race = {"Undead"}           -- Return to Podrig
