### ISSUE TITLE
Add a slider for "Show locations for next x steps"

### ISSUE THREAD

**Issue by max-ri** [max-ri/Guidelime#7]
- idea is to only show [L]s of currently active step (default = 1 ?)
- should be connected to/replace "Number of map markers"
  -e.g. "Show target locations for next x steps"(=[G)) / "Show additional locations for next x steps"(=[L])
- also connected to slider "Number of steps shown"
- suggested by ettern#2157, lag#9498

**Comment by max-ri** [comment]
connection with #21

**Comment by ettern** [comment]
Example with [L]'s
`From now on focus on [QC5441 Lazy Peons] (See <staticIcon> on map for locations) while picking up cactus apples for [QC4402 Galgar's Cactus Apple Surprise] and killing scorpids for [QC789 Sting of the Scorpid].[L 41.2,72.7][L 42.3,73.2][L 44.7,72.8][L 47.6,69.4][L 45.6,65.7][L 47.2,65.5][L 46.8,60.8][L 47.1,57.9][L 43.8,57.8][L 42.7,57.4][L 41.3,58.8][L 40.9,60.4][L 38.8,61.9]`

In this step I would like to show locations for Lazy Peons ([L]'s). These locations should not be visible in Guidelime step panel and their marker icon should be replaced with a static icon (a simple circle or something).
<img width="421" alt="StepsPanel" src="https://user-images.githubusercontent.com/3115678/62422508-0ffb3280-b6b4-11e9-9b46-1caae14f7fef.png">
<img width="259" alt="map" src="https://user-images.githubusercontent.com/3115678/62422514-302af180-b6b4-11e9-9952-6ec49546615a.png">


Additionally, locations should only be shown once this step is active. And they should be removed when this step is [complete.]

**Comment by max-ri** [comment]
Correct. The [L] markers
- do not need to have numbered map markers,
- do not need more than one icon when there is more than one on one step,
- it would be enough to show them for the active step(s).
my only concern with this change would be how to change the options (although i will have to organize those somehow anyway -> #21).
right now there is "number of steps shown" (defaults to unlimited) and "number of map markers" (defaults to 10)
im thinking about changing the latter eg to "number of steps to show target locations for" (could default to 10 or also unlimited) and add "number of steps to show additional locations for" (could default to 1 so that they only show up for the active step).
