### ISSUE TITLE
Bug: popup box in the editor

### ISSUE THREAD

**Issue by Offroads** [max-ri/Guidelime#71]
When you double click on questnames / questid's etc. it will open the popup box.

Currently it opens regardless of whether or not you click the same item. So if you click on two different items within a short timeframe (1,5 sec?) you will end up opening the popup window for the 2nd one.
Suggestion: Check if the same item is selected twice. If it is a different one - don't open the popup box.

**Comment by max-ri** [comment]
Can you maybe add a screenshot to describe the problem?

**Comment by Offroads** [comment]
![image](https://user-images.githubusercontent.com/28876369/63212595-4ea6d900-c107-11e9-8535-e84f97b9c928.png)
If you click once 1(QT4402), 2(QT789), 3(QT794) it will open 
![image](https://user-images.githubusercontent.com/28876369/63212620-a3e2ea80-c107-11e9-9442-ca19ab2b77e1.png)
Even though you didn't double click QT789.

**Comment by max-ri** [comment]
gotcha. fixed. ty for reporting.
