### ISSUE TITLE
Options error

### ISSUE THREAD

**Issue by Nillx** [max-ri/Guidelime#88]
Getting this error when i open the settings

2x Guidelime\Guidelime-0.037-Beta.lua:1183: attempt to index field 'options' (a nil value)
Guidelime\Guidelime-0.037-Beta.lua:1183: in function <Guidelime\Guidelime.lua:1181>

Locals:
(*temporary) = nil
(*temporary) = false
(*temporary) = nil
(*temporary) = "attempt to index field 'options' (a nil value)"
addon = <table> {
 setArrowTexture = <function> defined @Guidelime\Guidelime_Map.lua:157
 showEditPopupQUEST = <function> defined @Guidelime\Guidelime_Editor.lua:433
 showEditPopupNEXT = <function> defined @Guidelime\Guidelime_Editor.lua:197
 showEditPopupDETAILS = <function> defined @Guidelime\Guidelime_Editor.lua:239
 class = "Warlock"
 loadGuide = <function> defined @Guidelime\Guidelime_Guides.lua:6
 races = <table> {
 }
 showEditPopupAPPLIES = <function> defined @Guidelime\Guidelime_Editor.lua:341
 createPopupFrame = <function> defined @Guidelime\Guidelime_Frames.lua:130
 COLOR_LEVEL_YELLOW = "|cFFFFFF00"
 showArrow = <function> defined @Guidelime\Guidelime_Map.lua:213
 mapIcons = <table> {
 }
 COLOR_INACTIVE = "|cFF666666"
 showGuides = <function> defined @Guidelime\Guidelime_Guides.lua:276
 SPECIAL_MAP_INDEX = <table> {
 }
 showOptions = <function> defined @Guidelime\Guidelime_Options.lua:457
 importPlainText = <function> defined @Guidelime\Guidelime_Import.lua:326
 getClass = <function> defined @Guidelime\Data\Guidelime_Data.lua:26
 getQuestFactionQuestie = <function> defined @Guidelime\Data\Guidelime_Questie.lua:50
 factions = <table> {
 }
 showEditPopupNAME = <function> defined @Guidelime\Guidelime_Editor.lua:197
 GUIDE_LIST_URL = "https://github.com/max-ri/guidelime/wiki/GuideList"
 creaturesDB = <table> {
 }
 containsKey = <function> defined @Guidelime\Data\Guidelime_Data.lua:77
 COLOR_LEVEL_GRAY = "|cFF808080"
 addCheckbox = <function> defined @Guidelime\Guidelime_Frames.lua:55
 COLOR_LIGHT_BLUE = "|cFF99CCFF"
 getQuestPositions = <function> defined @Guidelime\Data\Guidelime_QuestsTools.lua:144
 addQuestCoordinates = <function> defined @Guidelime\Guidelime_EditorTools.lua:33
 COLOR_LEVEL_RED = "|cFFFF1400"
 arrowX = 1667.860000
 AUTO_COMPLETE_DELAY = 0.010000
 getPossibleQuestIdsByName = <function> defined @Guidelime\Data\Guidelime_QuestsTools.lua:393
 addCheckOption = <function> defined @Guidelime\Guidelime_Frames.lua:69
 updateFromQuestLog = <function> defined @Guidelime\Guidelime_Events.lua:33
 getQuestPositionsQuestie = <function> defined @Guidelime\Data\Guidelime_Questie.lua:58
 showEditor = <function> defined @Guidelime\Guidelime_Editor.lua:714
 showEditPopupGUIDE_APPLIES = <function> defined @Guidelime\Guidelime_Editor.lua:341
 loadData = <function> defined @Guidelime\Guidelime.lua:101
 DEFAULT_GOTO_RADIUS = 10
 codes = <table> {
 }
 getQuestObjectivesQuestie = <function> defined @Guidelime\Data\Guidelime_Questie.lua:171
 optionsFrame = <unnamed> {
 }
 testLocalization = <function> defined @Guidelime\Localization.lua:992
 addQuestTag = <function> defined @Guidelime\Guidelime_EditorTools.lua:57
 xp = 0
 showMapIcons = <function> defined @Guidelime\Guidelime_Map.lua:137
 COLOR_LEVEL_GREEN = "|cFF008000"
 updateArrow = <function> defined @Guidelime\Guidelime_Map.lua:186
 showUrlPopup = <function> defined @Guidelime\Guidelime_Frames.lua:192
 getQuestClasses = <function> defined @Guidelime\Data\Guidelime_QuestsTools.lua:38
 face = 2.809388
 raceIDs = <table> {
 }
 race = "Undead"
 L = <table> {
 }
 updateMainFrame = <function> defined @Guidelime\Guidelime.lua:961
 isFaction = <function> defined @Guidelime\Data\Guidelime_Data.lua:51
 updateSteps = <function> defined @Guidelime\Guidelime.lua:900
 firstLogUpdate = true
 contains = <function> defined @Guidelime\Data\Guidelime_Data.lua:62

**Comment by max-ri** [comment]
is fixed. ty for reporting.
