### ISSUE TITLE
Lots of errors when i enter in RFC

### ISSUE THREAD

**Issue by Nillx** [max-ri/Guidelime#89]
This started to pop up when i entered in Fragefire Chasm

372x Guidelime\Guidelime_Map.lua:200: attempt to perform arithmetic on field 'x' (a nil value)
Guidelime\Guidelime_Map.lua:200: in function <Guidelime\Guidelime_Map.lua:196>

Locals:
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = 989.639899
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = 389
(*temporary) = "attempt to perform arithmetic on field 'x' (a nil value)"
addon = <table> {
 setArrowTexture = <function> defined @Guidelime\Guidelime_Map.lua:167
 showEditPopupQUEST = <function> defined @Guidelime\Guidelime_Editor.lua:433
 showEditPopupNEXT = <function> defined @Guidelime\Guidelime_Editor.lua:197
 showEditPopupDETAILS = <function> defined @Guidelime\Guidelime_Editor.lua:239
 class = "Warlock"
 loadGuide = <function> defined @Guidelime\Guidelime_Guides.lua:6
 races = <table> {
 }
 showEditPopupAPPLIES = <function> defined @Guidelime\Guidelime_Editor.lua:341
 createPopupFrame = <function> defined @Guidelime\Guidelime_Frames.lua:130
 COLOR_LEVEL_YELLOW = "|cFFFFFF00"
 showArrow = <function> defined @Guidelime\Guidelime_Map.lua:225
 mapIcons = <table> {
 }
 COLOR_INACTIVE = "|cFF666666"
 showGuides = <function> defined @Guidelime\Guidelime_Guides.lua:276
 SPECIAL_MAP_INDEX = <table> {
 }
 showOptions = <function> defined @Guidelime\Guidelime_Options.lua:496
 importPlainText = <function> defined @Guidelime\Guidelime_Import.lua:326
 getClass = <function> defined @Guidelime\Data\Guidelime_Data.lua:26
 getQuestFactionQuestie = <function> defined @Guidelime\Data\Guidelime_Questie.lua:50
 factions = <table> {
 }
 showEditPopupNAME = <function> defined @Guidelime\Guidelime_Editor.lua:197
 GUIDE_LIST_URL = "https://github.com/max-ri/guidelime/wiki/GuideList"
 creaturesDB = <table> {
 }
 containsKey = <function> defined @Guidelime\Data\Guidelime_Data.lua:77
 COLOR_LEVEL_GRAY = "|cFF808080"
 flightmasterDB = <table> {
 }
 addCheckbox = <function> defined @Guidelime\Guidelime_Frames.lua:55
 COLOR_LIGHT_BLUE = "|cFF99CCFF"
 getQuestPositions = <function> defined @Guidelime\Data\Guidelime_QuestsTools.lua:148
 addQuestCoordinates = <function> defined @Guidelime\Guidelime_EditorTools.lua:33
 COLOR_LEVEL_RED = "|cFFFF1400"
 arrowX = 989.639899
 AUTO_COMPLETE_DELAY = 0.010000
 getPossibleQuestIdsByName = <function> defined @Guidelime\Data\Guidelime_QuestsTools.lua:411
 addCheckOption = <function> defined @Guidelime\Guidelime_Frames.lua:69
 updateFromQuestLog = <function> defined @Guidelime\Guidelime_Events.lua:33
 getQuestPositionsQuestie = <function> defined @Guidelime\Data\Guidelime_Questie.lua:58
 showEditor = <function> defined @Guidelime\Guidelime_Editor.lua:714
 showEditPopupGUIDE_APPLIES = <function> defined @Guidelime\Guidelime_Editor.lua:341
 loadData = <function> defined @Guidelime\Guidelime.lua:101
 DEFAULT_GOTO_RADIUS = 10
 codes = <table> {
 }
 getQuestObjectivesQuestie = <function> defined @Guidelime\Data\Guidelime_Questie.lua:171
 optionsFrame = <unnamed> {
 }
 testLocalization = <function> defined @Guidelime\Localization.lua:1064
 addQuestTag = <function> defined @Guidelime\Guidelime_EditorTools.lua:57
 completeSemiAutomaticByType = <function> defined @Guidelime\Guidelime.lua:1008
 xp = 5120
 showMapIcons = <function> defined @Guidelime\Guidelime_Map.lua:145
 COLOR_LEVEL_GREEN = "|cFF008000"
 updateArrow = <function> defined @Guidelime\Guidelime_Map.lua:196
 showUrlPopup = <function> defined @Guidelime\Guidelime_Frames.lua:192
 getQuestClasses = <function> defined @Guidelime\Data\Guidelime_QuestsTools.lua:42
 raceIDs = <table> {
 }
 race = "Undead"
 L = <table> {
 }
 updateMainFrame = <function> defined @Guidelime\Guidelime.lua:1046
 isFaction = <function> defin

**Comment by max-ri** [comment]
ty for reporting! fixed.
